### ISSUE TITLE
add more field to search columns

### ISSUE THREAD

**Issue by witwall** [dpgaspar/Flask-AppBuilder#1082]
If you'd like to report a bug in Flask-Appbuilder, fill out the template below. Provide
any extra information that may be useful

### Environment

Flask-Appbuilder version:
Flask-AppBuilder==2.1.6
pip freeze output:

### Describe the expected results
how to add more columns to search columns
Tell us what should happen.

```python
class Material(db.Model):
    __tablename__ = 'material'
    id = db.Column(db.Integer, primary_key=True, server_default=db.FetchedValue())
    supplier_code = db.Column(db.Text, nullable=False, unique=True)
    supplier_name = db.Column(db.Text, nullable=False)
    name = db.Column(db.Text, nullable=False)
    width = db.Column(db.Integer, nullable=False)

class StockView(db.Model):
    # __bind_key__ = 'Material'
    __tablename__ = 'stock_view'
    id = db.Column(db.Integer, primary_key=True, server_default=db.FetchedValue())
    in_date = db.Column(db.Date, server_default=db.FetchedValue(),default=datetime.date.today(),)
    supplier_barcode = db.Column(db.Text)
    production_date = db.Column(db.Date)
    expiry_date = db.Column(db.Date)
    thickness = db.Column(db.Integer)
    gross_weight = db.Column(db.Numeric)
    material_id = db.Column(db.ForeignKey('material.id'), nullable=False)
    material = db.relationship('Material')
```
I want to in stock list, I can filter with Material.supplier_code, Material.supplier_name, Material.name, Material.width too.

### Describe the actual results

Tell us what happens instead.
only show columns in stock table, no columns in foreign table material.

```pytb
Paste the full traceback if there was an exception.
```

**Comment by witwall** [comment]
no exception, but only can be filtered with the columns in stock table, and also relation column, material, I wish there is an easy way to filter with supplier_code, supplier_name, name, width too.

for example, I can filter stock with supplier_name and width. 


thanks in advance.

**Comment by pcn70** [comment]
I am really really interested in it too.
I am trying to do the same thing (to add search filters based on columns from related table) but with no success at all.
I hope that someone could explain how to do it because in Flask Appbuilder documentation and in the examples found on the web I couldn't find anything similar (my fault 99%).
Thanks a lot!

**Comment by Yoyasp** [comment]
I've been looking into this for a week as well now.
I've tried adding an extra property into the model using a join with a relationship. (like in https://github.com/dpgaspar/Flask-AppBuilder/issues/73).

This makes the column show up in the add filters view as a many-to-many column with the desired filters. Hoewever because im using a many-to-one relationship this does not actualy filter any results...

I can make the desired value show up in the list by adding a dotted notation inside the list_column on the ModelView. But because its not in the actual model i cant filter or sort on that column.

I've also looked into creating my own Filter with a custom FilterConverter, but this is not working because of the same reason.

Did anyone else have any luck with this?

**Comment by drummerwolli** [comment]
@dpgaspar any chance this is possible by now? basically making `search_columns` also understand relationship columns, like:

```python
class StockModelView:
    datamodel = SQLAInterface(StockView)
    search_columns = ["material.supplier_code"]
```

currently you can only specify the columns of `StockView`, like `search_columns = ["material"]`. But extending this would be very helpful.
