### ISSUE TITLE
Filtering openapi endpoints does not work in version 2.2.1 and above

### ISSUE THREAD

**Issue by ThomasP0815** [dpgaspar/Flask-AppBuilder#1301]
First Issue:

{
  "columns": [
    "string"
  ],
  "filters": [
    {
      "col": "string",
      "opr": "string"
    }
  ],
  "keys": [
    "list_columns"
  ],
  "order_column": "string",
  "order_direction": "asc",
  "page": 0,
  "page_size": 0
}

![image](https://user-images.githubusercontent.com/30863072/75777024-7a14ac80-5d55-11ea-8c4d-78e246cd8ad0.png)

Second Issue:

{
  "columns": [
    "string"
  ],
  
  "keys": [
    "list_columns"
  ],
  "order_column": "string",
  "order_direction": "asc",
  "page": 0,
  "page_size": 0
}

![image](https://user-images.githubusercontent.com/30863072/75777134-b0522c00-5d55-11ea-9333-a9fc43f1729f.png)

Working:

{
  "columns": [
    "string"
  ],
  
  "keys": [
    "list_columns"
  ],
  
  "order_direction": "asc",
  "page": 0,
  "page_size": 0
}

![image](https://user-images.githubusercontent.com/30863072/75777244-eb545f80-5d55-11ea-9dce-3180b4f6734a.png)

**Comment by dpgaspar** [comment]
Hi @ThomasP0815,

Thank you for reporting this.

First error, throws an exception because filters should have:
```
"filters": [
    {
      "col": "string",
      "opr": "string",
      "value": "string"
    }
  ]
```
By default it's missing the value key. Flask-AppBuilder should not raise 500 on this, I'll make a fix ASAP.

Second error:
column `string` does not exist, so it's response is HTTP 400, looks good
