### ISSUE TITLE
Search and Group buttons to 'related_views' table

### ISSUE THREAD

**Issue by blacklupo** [dpgaspar/Flask-AppBuilder#145]
There is any possibility to create a Search bar and Group buttons to a 'related_view' table in a MasterDetailView? 

By now I create a template which includes the Search bar, but the Search bar in this case is related to the MasterDetailView table.

Any suggestion or advice?

Thanks

P.D: This is the template created by me:

```html
{% extends "appbuilder/base.html" %}
{% import 'appbuilder/general/lib.html' as lib %}

{% block content %}

        <div class="col-lg-{{ master_div_width}} col-md-{{ master_div_width}} container">
            {{ lib.panel_begin(title) }}
       	        {{ widgets.get('list')()|safe }}
            {{ lib.panel_end() }}
        </div>
            {% for view in related_views %}
                <div class="col-lg-{{ 12 - master_div_width}} col-md-{{ 12 - master_div_width}} container">
                {{ lib.panel_begin(view.list_title) }}
                    {% block list_search scoped %}
		                {% call lib.accordion_tag("accordion1",_("Search"), False) %}
                        {{ widgets.get('search')()|safe }}
		                {% endcall %}
                    {% endblock %}
                    <div>
                        {{ widgets.get('related_views')[loop.index - 1](pk = pk)|safe }}
                    </div>
                {{ lib.panel_end() }}
                </div>
            {% endfor %}

{% endblock %}
```

**Comment by dpgaspar** [comment]
Hello,

Good question, The issue here is that the server is not sending any search widget to the template.

There are some problems to solve:

- The submitted get request from the search form should be merged with the current pk.
- A way to get the related_view search widget (currently there is none).

There is a major problem to this, if one would want to support multiple related views, there is currently no easy way to include multiple search widgets sending queries to the same endpoint. The current framework query string is:

_flt_<COL_NAME>_<FILTER_INDEX>=<VALUE>

There is no information regarding the related_view name so the server would not know to which related view the query is intended to. On query parameters for order by there is one:

_oc_<VIEW_NAME>=<COL_NAME> + od_<VIEW_NAME>=asc|desc

So i guess this is possible (developing a new server class view) if your supporting only one related_view. Because of this, it is not a candidate for a new feature. If this is important to you i can help you dev the server class view.

**Comment by blacklupo** [comment]
Hi Daniel, sorry for the delay, I think that this not be necessary.

Thank you so much for the support! :)

**Comment by dpgaspar** [comment]
No problem!

**Comment by Cody-Steelman** [comment]
Hello, this would help out with what were working on with this project, if this were to be implemented on searching one related_view, are you still willing to help develop the server class view that you mentioned that is required to search the related view?
