### ISSUE TITLE
How to use OR operation in Rison

### ISSUE THREAD

**Issue by HugoPu** [dpgaspar/Flask-AppBuilder#1516]
In the docunment, I found we can use `AND` operations like this `(filters:!((col:name,opr:sw,value:a),(col:name,opr:ew,value:z)))`, but how to use `OR` operation?

**Comment by dpgaspar** [comment]
You can't use `OR` by default, it would require a more complex data structure since you can't freely mix AND's and OR's.
Yet there is a simple solution, you can make custom filters and develop what ever logic/filter you need:

https://github.com/apache/incubator-superset/blob/master/superset/dashboards/filters.py#L31

Then on your `ModelRestApi`:

https://github.com/apache/incubator-superset/blob/master/superset/dashboards/api.py#L172
