### ISSUE TITLE
Airflow User Creation DOS with wrong Roles

### ISSUE THREAD

**Issue by gaurav1008** [dpgaspar/Flask-AppBuilder#1554]
If you'd like to report a bug in Flask-Appbuilder
### Environment

Flask-Appbuilder version: 1.13.1 , 2.3.4, 3.1.1

pip freeze output:
Originally identified in env:
Airflow 1.10.10
https://raw.githubusercontent.com/apache/airflow/constraints-1.10.10/constraints-2.7.txt

Retested on below: Issue reproduced.
Airflow 1.10.14
https://raw.githubusercontent.com/apache/airflow/constraints-1.10.14/constraints-3.6.txt

Airflow 2.0.0
https://raw.githubusercontent.com/apache/airflow/constraints-2.0.0/constraints-3.6.txt

### Describe the expected results

When submitting a request for a new user from Airflow UI, if an incorrect role is send from Burp tool, the user is created without any issue, but when that user tries to login from UI, it gets DOS. In DB there is no role created for the same and validation does happen somewhere but no failure is prompt on UI and user creation doesn't fails.

We reported the issue to Airflow security team but they declined it as a security issue and suggested to report it in this forum. 

```python
NA
```

### Describe the actual results
User is created with wrong roles(empty roles) in DB causing this user to have DOS. 

```pytb
NA
```

### Steps to reproduce

Please see attached document
_[Airflow1.10.10_UserRole_DOSAttack.docx](https://github.com/dpgaspar/Flask-AppBuilder/files/5874301/Airflow1.10.10_UserRole_DOSAttack.docx)_

**Comment by dpgaspar** [comment]
Hi @gaurav1008 thank you for reporting,

I've tested this using `Burp` on a simple FAB app (and Superset), but the user behaviour does not end up being an infinite redirect has described on AirFlow, The user successfully logins but does not have access to anything (has expected). In fact it's possible to create a user without any role that translates to the same behaviour.

IMO categorising this finding has a DOS is not correct since only the badly created user is affected. Unless Airflow would globally crash.

I would argue that this is a security problem since an Admin can do basically everything on an application, for example deleting all users.

**Comment by gaurav1008** [comment]
We can ignore Admin user for a second. If we have a user which has perm to create new user and define roles, issue will be same. My reason to believe it to be DOS is that newly created user is not allowed to do anything on Application and he doesn't receives any failure on UI. Note- admin user may not be an operator. He is just a sys admin. 

But I understand the fact , may be that n number of redirection can be an issue from airflow UI (and not appBuilder). 
Issue boils up when user with no roles is allowed to login , the redirects starts. 

I again one more test. I created a user without any role from UI. And guess what, same redirection happened.

**Comment by dpgaspar** [comment]
The redirection seems like an Airflow issue. But I do agree that the UI should show an error, I'll fix that

**Comment by gaurav1008** [comment]
Any luck with the fix ?
