### ISSUE TITLE
Can't get simple angularJS to call python function

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#156]
in /templates/mybaselist.html:

```HTML5
{% extends "appbuilder/general/model/list.html" %}

<!--Path location-->
<!--/Users/Seb/PycharmProjects/sampleproj/app/static/css/your_css_file.css-->
<!--/Users/Seb/PycharmProjects/sampleproj/app/static/js/app.js-->
<!--/Users/Seb/PycharmProjects/sampleproj/app/static/bower_components/angular/angular.min.js-->
<!--/Users/Seb/PycharmProjects/sampleproj/app/templates/mybaselist.html <- this file -->

{% block head_js %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/your_js_file.js')}}"></script>
{% endblock %}

{% block head_css %}
    {{ super() }}
    <script src="{{url_for('static', filename='css/your_css_file.css')}}"></script>
{% endblock %}

{% block tail_js %}
    {{ super() }}
    <script src="{{url_for('static',filename='bower_components/angular/angular.min.js')}}"></script>
{% endblock %}
```

and in /templates/mySample.html:
```HTML5
{% extends "mybaselist.html" %}
{% block list_search scoped %}
    {{ super() }}
    <body ng-app="">
       <button ng-click="count=count+1" ng-init="count=0">Click Me</button>
            count: {{count}}
    </body>
 {% endblock %}

```
But count does not update on each click? Starts off as blank and continues to be blank on click? 
Or in general where to place <html ng-app> since this seems to be embedded in the Flask-AppBuilder templates?

**Comment by dpgaspar** [comment]
First of all your not calling any python function, AngularJS runs on the client. send me the output from **pip list** to get you pkg versions.

**Comment by dpgaspar** [comment]
- What is mySample.html is it your override for **list_template** on ModelView?
- You should not use <body> here the train already left on block **list_search** use

``` html
{% block content %}
{{ super() }}
<div  ng-app="FAB" >
{% endblock %}

```

Another problem, is that Jinja2 uses {{ ... }} and {% .. %} and so does AngularJS, so you must "tell" AngularJS to use a different mark. Create a file on your static folder named app.js.

``` js
var app = angular.module('FAB', []);

app.config(['$interpolateProvider', function($interpolateProvider) {
  $interpolateProvider.startSymbol('{[');
  $interpolateProvider.endSymbol(']}');
}]);

```
Now when using AngularJS use {[ ... ]} instead of {{ .. }}

Final problem, if i really go forward on including AngularJS, your work will probably need to be changed. If this is all because of the cascading list's one possible solution is to use a list with the two values concatenated.
