### ISSUE TITLE
created/changed_by_fk issues updating database outside of FAB framework

### ISSUE THREAD

**Issue by cbisaccia78** [dpgaspar/Flask-AppBuilder#1626]
**PROBLEM:** 

We have a database class (call it Collection), which inherits the AuditMixin mixer. This mixer automatically generates the fields "created_by_fk" and "changed_by_fk" for every insert/update to the table. 

In our application we have asynchronous tasks that must run outside of the FAB thread. When the tasks finish, they update a column in Collection. However, the AuditMixin does not have access to a valid g.user in order to generate the user_id for these updates. 

**ATTEMPTED SOLUTION (FAILED):**

I imported the g global in the task thread and passed it the user id which initiated the call.

Then I tried to spoof the g.user.id for AudixMixin in the following way: 

```
class UserSpoof:  
        def __init__(self, _id):  
            self.id = _id  
.
.
.
def run_task(user_id):
       with app.app_context():
               g.user = UserSpoof(user_id)
               .
               .
               .
               Collection.update_status('finished')
```
**QUESTION**
Do you have any suggestions on how we should solve this issue?

**Comment by soundmaking** [comment]
from reply to a similar question on the Gitter chat thing - https://gitter.im/dpgaspar/Flask-AppBuilder?at=6013595e1ed88c58d8073f09 :

... I had a situation where some types of record can be created by actions of non-registered users... Because of the `return None` in this AuditMixin method:
```python
    @classmethod
    def get_user_id(cls):
        try:
            return g.user.id
        except Exception:
            return None
```
I added a User to the db and took note of the id number... in this case the id happened to 99... I now use this class to mixin where needed:
```python
class AuditMixinExtra(AuditMixin):
    """to work with this app's database permitting edits by 'unknown' user
    """
    def get_user_id(cls):
        try:
            return g.user.id
        except Exception:
            return 99  # 99 is id of User setup as 'unknown user' in the db
```
(hard-coding the id that way is a bit ugly: could be set via config or something)
