### ISSUE TITLE
Question: What Python 3 LDAP module do I need to install?

### ISSUE THREAD

**Issue by pchernik** [dpgaspar/Flask-AppBuilder#200]
What Python 3 LDAP module do I need to install to get Flask-AppBuilder working with LDAP authentication?

I tried both ldap3 and python3-ldap and neither one seem to work, I keep getting:

Exception: No ldap library for python.

**Comment by pchernik** [comment]
python3-ldap doesn't seem to work either

**Comment by pchernik** [comment]
I ended up installing python-ldap fork that support python3 via:
pip3 install git+https://github.com/rbarrois/python-ldap.git@py3

If someone has experience with this, would be great to get confirmation whether this is the right approach. Thanks!

**Comment by myliyifei** [comment]
Q: Does it work with Python 3?

A1: No. Due to time constraints.
A2: There's an independent fork not related to this project.
https://github.com/pyldap/pyldap

for python2 http://thefourtheye.in/2013/04/20/installing-python-ldap-in-ubuntu/

import for python3:  
sudo apt-get install python3-dev(rather than python-dev)
pip3 install pyldap
