### ISSUE TITLE
Python3 error 

### ISSUE THREAD

**Issue by philliproso** [dpgaspar/Flask-AppBuilder#24]
Very cool project with full bootstrap 3 prettiness. 

In the docs there is no mention of python 3 support. 

I am guessing something to do with babel. This is once I try to load a page. 
TypeError: Unxpected value for identifier: b'en'

**Comment by anddam** [comment]
The python-babel PR has been merged in https://github.com/python-babel/babel/pull/301 ,  is the Py3 limitation still in place as per documentation?

**Comment by dpgaspar** [comment]
I've migrated from flask-babelpkg (a fork of mine, to allow multiple translation sources at the same time) to flask-babel. My test on python 3.5 were successful. I need to update the docs

**Comment by anddam** [comment]
Good to know, do you want a new issue to remember updating the docs?

**Comment by absinthetized** [comment]
hello.

got the issue here.

ubuntu 16.04, python 3.5 in venv (virtualenv --always-copy for the sake...).

I've used fabmanager to download the skeleton app. _b'en'_ appears. Last week I've poked a bit with code to patch it. then Suddently the issue disappeared... :-/

Now again I've created a new venv, pip'ed fab, downloaded the skeleton: _b'en'_ pops up again!

Now this is what I've done in babel/manager.py _get_locale()_ method:
```
locale = session.get('locale')
if str(locale)[0] == 'b':
   locale = str(locale).split("'")[1]
   session['locale'] = locale
if locale:
   return locale
session['locale'] = self.babel_default_locale
return session['locale']
```

Bad patch, nice thing: it works and if I remove the patch **after** a run of it, the system still runs great, like if a cache was in place :-/ WEIRD.

Still rude for a pull request so I've just dropped few lines here FYI.

Following the pip freeze:

> Babel==2.3.4
> click==6.6
> colorama==0.3.7
> defusedxml==0.4.1
> Flask==0.11.1
> Flask-AppBuilder==1.8.1
> Flask-Babel==0.11.1
> Flask-Login==0.2.11
> Flask-OpenID==1.2.5
> Flask-SQLAlchemy==2.0
> Flask-WTF==0.12
> itsdangerous==0.24
> Jinja2==2.8
> MarkupSafe==0.23
> pkg-resources==0.0.0
> psycopg2==2.6.2
> python3-openid==3.0.10
> pytz==2016.6.1
> SQLAlchemy==1.0.15
> uWSGI==2.0.13.1
> Werkzeug==0.11.11
> WTForms==2.1
