### ISSUE TITLE
menu access right lost after server reload 

### ISSUE THREAD

**Issue by wycwyx** [dpgaspar/Flask-AppBuilder#240]
AppBuilder's method add_view will delete the menu_access privilege for all views because the baseview.base_permissions can't include it. So after every reload, the menu right will be lost except admin. 
Call Stack is :
    AppBuilder.add_view 
    AppBuilder._add_permission
    BaseSecurityManager.add_permissions_view

```
### the code from 742
            if perm_view.permission.name not in base_permissions:
                # perm to delete
                roles = self.get_all_roles()
                perm = self.find_permission(perm_view.permission.name)
                # del permission from all roles
                for role in roles:
                    self.del_permission_role(role, perm)
                self.del_permission_view_menu(perm_view.permission.name, view_menu)
### code end

The variable base_permissions has no 'menu_access'
```

**Comment by dpgaspar** [comment]
Can you help me reproduce this? don't see this happening!

**Comment by fabianmenges** [comment]
I was able to reproduce this and found the underlying issue. This happens when the class name of your view is the same as the name of the view e.g. 
**This is does not work:**
```
  class ManageStuff(BaseView):
  ...
  ...

  appbuilder.add_view(ManageStuff, 'ManageStuff',
  label=__("ManageStuff"),
  category="",
  category_icon="")
```
**This does work:**
```
  class ManageStuffView(BaseView):
  ...
  ...

  appbuilder.add_view(ManageStuffView, 'ManageStuff',
  label=__("ManageStuff"),
  category="",
  category_icon="")
```
The underlying problem is that when you create a new view it will create 2 different kind of permission entries. One with the view name one with the class name, if both strings are the same the permissions will override each other, which is what you saw in your call stack. This is a bug.
