### ISSUE TITLE
Profile /users/userinfo/ editable

### ISSUE THREAD

**Issue by gnud** [dpgaspar/Flask-AppBuilder#261]
Can the current user profile be edited ?

The only way to provide edit mode was to add another item in the right menu pointing to
/users/edit/{users_id}

Is there a better way ?

Thanks.

**Comment by valVk** [comment]
+1 
Want to know exact same answer to this question.

**Comment by dpgaspar** [comment]
That's the simplest way. But the UI would have two menu items, one for show and other for edit.

Another way would be to extend UserModelView or UserDBModelView:

https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/views.py#L202

- Expose a new method to render the edit form.
- Override the userinfo and show and add a new action that links to the edit form.

This would probably be a good candidate for a new feature. What do you think?

**Comment by gnud** [comment]
Can you write an example, where edit form for userinfo is implemented, so we can have it publicly, please ?
Thanks.

**Comment by dpgaspar** [comment]
Take a look at the current commit, it's still a bit beta. On profile view the user has an option to edit.

**Comment by gnud** [comment]
Looks good, one more thing, what permissions are needed to edit the user ?

**Comment by valVk** [comment]
Thanks

**Comment by dpgaspar** [comment]
can this form post on UserInfoEditView, can this form get on UserInfoEditView, userinfoedit on UserDBModelView.

This is still beta on master, and only available for auth DB.

**Comment by dpgaspar** [comment]
username and email, could be a "dangerous" to let user's change, think oauth for example.

I'm going to remove these.

Though It will be possible (and i hope easy) to override the userinfoedit form and add or remove new fields.

**Comment by gnud** [comment]
What do you mean by dangerous ?
Can we write data to the oauth provider ?

**Comment by dpgaspar** [comment]
No, nothing that dangerous, is just that if a user changes his/her username (using oauth) he/she will loose access.

The user registers himself (or is created) using a specific username for twitter (for example), if the user changes his user, the access will not be validated on twitter anymore.

**Comment by gnud** [comment]
There is a solution for that, what if we add additional column called oauth_user in User's table, this way we shall check against that column, instead of the our user column, so no matter which user is, the oauth user always stays :).

**Comment by dpgaspar** [comment]
That would imply a breaking release for everyone, with an upgrade procedure. Because we would have to migrate everyone's db schema, and copy email field or username to oauth_user.

You can extend the User Model and add whatever field you want. I've published a (i hope) nice example of this on: https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/extendsecurity
This example makes use of a new feature that let's you **base_filter** (or any other filters) with dotted notation. F.A.B. will make the necessary joins for you.

This version takes care also of "illegal" access to the API for filtered records on **base_filter**
