### ISSUE TITLE
routing on related view action

### ISSUE THREAD

**Issue by GregSilverman** [dpgaspar/Flask-AppBuilder#437]
I have several views with related views, where each related view has an action defined on them (to export selected records from that view). The action works fine on the views if access from each main view, but if I access them from a related view, such as:

```
class EncounterView(AuditedModelView):
    datamodel = SQLAInterface(Encounter)

    related_views = [LabView,
                     BasicVitalView,
                     DiagnosisView,
                     MedicationView,
                     ProcedureView]
```

Where an encounter can have Labs, BasicVitals, Diagnoses, etc. 

And, if I then go to the related view under the EncounterView, say LabView, to export Labs for the particular Encounter, after I confirm that I wish to perform the action, instead of redirecting to the LabView, it redirects to the first related view for the main view, in particular, BasicVitalsView (since it lists these alphabetically; or if I comment that out then DiagnosisView, etc.).

Is this a bug or a feature of using actions in related views? In particular, why is the action routing to the related BasicVitalView when I am issuing the action from the related LabView? The actions work fine on the standalone unrelated views (thus, if I go to the LabView and use the action there then it works fine). 

See attached images:

<img width="1151" alt="screen shot 2017-02-22 at 11 51 25 am" src="https://cloud.githubusercontent.com/assets/1007034/23224842/75a2ea62-f8f5-11e6-8449-ad70c720f4c9.png">

<img width="430" alt="screen shot 2017-02-22 at 11 32 14 am" src="https://cloud.githubusercontent.com/assets/1007034/23224805/5dfae630-f8f5-11e6-8d37-08a45854dff8.png">

<img width="486" alt="screen shot 2017-02-22 at 11 43 38 am" src="https://cloud.githubusercontent.com/assets/1007034/23224871/8accb29c-f8f5-11e6-9b87-a158b5405ea8.png">

**Comment by tomanizer** [comment]
I have an issue which is probably related to this:
**Actions on related views**

I have a mass-delete defined on a view.
It works fine when the view is called standalone and the action is performed on multiple items.
It also works fine when the action is performed on a single item in show view.

It does not work when the view is shows on a related view (using the show_cascade.html).
The action does not seem to properly trigger and it returns to the main index apge showing an access denied error and a 302 error in the console.

As described above the action does not seem to route correctly.
Not sure how to debug this, since it does not even seem to enter the function.
