### ISSUE TITLE
LDAP user registration: hex-encoded strings instead of human-readable

### ISSUE THREAD

**Issue by rumbin** [dpgaspar/Flask-AppBuilder#444]
I reported this on a side note in #432, but I feel, it would be more appropriate to file a new issue:

### Versions
* Python 3.4.5
```
Flask==0.12.1
Flask-AppBuilder==1.8.1
Flask-Babel==0.11.1
Flask-Cache==0.13.1
Flask-Login==0.2.11
Flask-Migrate==1.5.1
Flask-OpenID==1.2.5
Flask-Script==2.0.5
Flask-SQLAlchemy==2.0
Flask-Testing==0.6.1
Flask-WTF==0.14.2
superset==0.17.3
```

### Expected results
Logging in with a previously not registered user results in a new user account created from the information gathered from LDAP with all corresponding fields (fisrt name, last name,…) filled out correctly.

### Actual results
Login works and so does the creation of the user account. However, while the _username_ field is filled out correctly, other fields, such as _first_name_ or _last_name_:

![hex_problem](https://cloud.githubusercontent.com/assets/1220356/24693348/7216ccf2-19dd-11e7-8a9b-a903423a6229.PNG)

It should be noted that this behavior is only present in a python 3 environment. When run in a python 2.7 venv, everything works as expected.

**Comment by rumbin** [comment]
I forgot to mention: 
```
pyldap==2.4.28
```

**Comment by rumbin** [comment]
* Could anyone please give me a hint on how to debug this?
* Can anyone confirm this issue?

**Comment by bichkd** [comment]
I have the same issue, querying Oracle Virtual Directory.

```
Python 3.5.3
Flask            0.12.1
Flask-AppBuilder 1.8.1
Flask-Login      0.2.11
pyldap           2.4.25.1
superset         0.17.6
```

The first/last name and email fields come back hex-encoded (\x format). They do have the correct values, if decoded manually.

**Comment by mrhlee** [comment]
I got the same issue, but with bytes encoding instead of hex.
For me, the issue occurs within pyldap (version 2.4.28). You could try testing this with code similar to what's used in [manager.py](https://github.com/dpgaspar/Flask-AppBuilder/blob/1.8.1/flask_appbuilder/security/manager.py#L535) or in the sample code on pyldap's [readme](https://github.com/pyldap/pyldap#bytestext-management). The result for me had bytes on several fields, including name and email. I hope this helps.

**Comment by dpgaspar** [comment]
Were you able to nail it? 

Going to close this on, feel free to reopen if it's still relevant to you.

**Comment by rumbin** [comment]
Yes, unfortunately this issue is still unchanged. I tried all possible settings of bytes_mode, but with no success.

Any help for debugging would be greatly appreciated.

**Comment by rumbin** [comment]
@bichkd: Did you find any solution for this issue?

**Comment by dbichko** [comment]
@rumbin No, I have not.

I am happy to help test this in my environment, but I have no experience with Flask or AppBuilder (and very little with Python in general), so I won't be much help in debugging.

Why was the issue closed? It doesn't seem like anyone found a working solution.

**Comment by rumbin** [comment]
I do not understand why this issue was closed, as there was no progress whatsoever.

@dpgaspar Would you please reopen it?

**Comment by dpgaspar** [comment]
Hi @rumbin,

Sorry, i have no easy way of testing this, and this is probably a pyldap/ python 3.X / OpenLDAP issue.

This is where the LDAP info is retrieved: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/manager.py#L534

Please write a simple script mimicking this method, try to solve the problem, and/or give me some feedback then.

**Comment by rumbin** [comment]
I did some debugging and think I found a solution.
It turned out that our LDAP server returned the first_name and last_name as type bytes instead of str.
A simple test for this case, followed by a .decode() solves the issue.

In my quick and dirty solution I replaced the following part of function `auth_user_ldap` in file `security/manager.py`:
```
                    ldap_user_info = new_user[0][1]
                    if self.auth_user_registration and user is None:
                        user = self.add_user(
                                username=username,
                                first_name=ldap_user_info.get(self.auth_ldap_firstname_field, [username])[0],
                                last_name=ldap_user_info.get(self.auth_ldap_lastname_field, [username])[0],
                                email=ldap_user_info.get(self.auth_ldap_email_field, [username + '@email.notfound'])[0],
                                role=self.find_role(self.auth_user_registration_role)
                            )
```

Instead, I moved the LDAP lookups out of the self.add_user() call and converted the bytes to str, if necerssary:
```
                    ldap_user_info = new_user[0][1]
                    if self.auth_user_registration and user is None:
                        first_name=ldap_user_info.get(self.auth_ldap_firstname_field, [username])[0]
                        last_name=ldap_user_info.get(self.auth_ldap_lastname_field, [username])[0]
                        email=ldap_user_info.get(self.auth_ldap_email_field, [username + '@email.notfound'])[0],
                        # In some cases the extracted information is bytes instead of string.
                        if isinstance(first_name, bytes):
                            first_name = first_name.decode()
                        if isinstance(last_name, bytes):
                            last_name = last_name.decode()
                        if isinstance(email, bytes):
                            email = email.decode()
                        user = self.add_user(
                                username=username,
                                first_name=first_name,
                                last_name=last_name,
                                email=email,
                                role=self.find_role(self.auth_user_registration_role)
                            )
```

As I don't know if it may happen that the email field can be bytes as well, it is treated like the other two fields.

@dpgaspar I don't think that my coding style meets DRY and other coding conventions. Thus I would appreciate if you could implement this functionality in a more pleasant fashion.

**Comment by dpgaspar** [comment]
What type/version of LDAP server are you running?

**Comment by rumbin** [comment]
The LDAP server a Microsoft AD Global Catalog, provided by Microsoft Server 2012 R2.
I hope this information is sufficient.

**Comment by dpgaspar** [comment]
This could be related to this:
https://stackoverflow.com/questions/24647772/ad-property-is-system-byte-which-encoding-to-convert-to-string

So Server 2012R2 is implementing LDAPv3
https://technet.microsoft.com/en-us/library/cc961766.aspx

If your using, pyldap, looks like they have released 2.4.37 some days ago, with some fixes. Test the upgrade and if it does not solve it, open an issue on their side.

Thks!

**Comment by laranzu** [comment]
I just ran into this problem as well with Flask_AppBuilder under Python3 and pyldap instead of python-ldap. Patch for security/manager.py below. Should be backwards compatible with Python2, still works if pyldap one day returns str instead of bytes.

--- lib/python3.5/site-packages/flask_appbuilder/security/manager.py	2017-07-13 10:51:38.040871143 +1000
+++ mylib/python3.5/site-packages/flask_appbuilder/security/manager.py	2017-07-13 10:44:55.738471539 +1000
@@ -645,9 +645,9 @@
                     if self.auth_user_registration and user is None:
                         user = self.add_user(
                                 username=username,
-                                first_name=ldap_user_info.get(self.auth_ldap_firstname_field, [username])[0],
-                                last_name=ldap_user_info.get(self.auth_ldap_lastname_field, [username])[0],
-                                email=ldap_user_info.get(self.auth_ldap_email_field, [username + '@email.notfound'])[0],
+                                first_name=ldap_user_info.get(self.auth_ldap_firstname_field, [username])[0].decode('utf-8'),
+                                last_name=ldap_user_info.get(self.auth_ldap_lastname_field, [username])[0].decode('utf-8'),
+                                email=ldap_user_info.get(self.auth_ldap_email_field, [username + '@email.notfound'])[0].decode('utf-8'),
                                 role=self.find_role(self.auth_user_registration_role)
                             )
 
@@ -655,12 +655,8 @@
                 return user
 
             except ldap.LDAPError as e:
-                if type(e.message) == dict and 'desc' in e.message:
-                    log.error(LOGMSG_ERR_SEC_AUTH_LDAP.format(e.message['desc']))
-                    return None
-                else:
-                    log.error(e)
-                    return None
+                log.error(e)
+                return None
 
     def auth_user_oid(self, email):
         """

**Comment by laranzu** [comment]
just ran into this problem as well with Flask_AppBuilder under Python3 and pyldap instead of python-ldap. Patch for security/manager.py attached
[flask_appbuilder_LDAP.txt](https://github.com/dpgaspar/Flask-AppBuilder/files/1143764/flask_appbuilder_LDAP.txt)
. Should be backwards compatible with Python2, still works if pyldap one day returns str instead of bytes.

**Comment by rumbin** [comment]
@dpgaspar: It looks like the issue is back to FAP. See [https://github.com/pyldap/pyldap/issues/110](https://github.com/pyldap/pyldap/issues/110)

**Comment by dpgaspar** [comment]
Ok, thank you for reporting it to pyldap, i'll make the advised changes and include them on the next release (this should be out this week).

**Comment by rumbin** [comment]
Thanks a lot for your effort!

**Comment by dpgaspar** [comment]
Not time to release last week. Made the advised changes, are you able to test it (develop branch) ?

**Comment by rumbin** [comment]
I'll try to test it as soon as possible...

**Comment by rumbin** [comment]
Success! The develop branch fixes this issue.
Thank our once more!

**Comment by dpgaspar** [comment]
Great, going to release it ASAP.

**Comment by laranzu** [comment]
Also confirm that the new develop branch fixes the issue.

**Comment by dpgaspar** [comment]
V1.9.3 is out
