### ISSUE TITLE
Display a view by linking to it?

### ISSUE THREAD

**Issue by AustinJim** [dpgaspar/Flask-AppBuilder#462]
Hi all,
I am using FAB for admin of users and data. I want to create a web page where the user just has to log in and immediately sees this page. I don't want to display the normal menu. I've tried this:
```
@app.route("/votingView", methods=['GET','POST'])
class VotingView(ModelView):
    datamodel = SQLAInterface(Registration)
    name = "VotingView"
    related_views = [CarClassView]
    label_columns = {'CarClass':'Class', 'CarClass.Marque':'Marque','CarClass.Title' : 'ClassName', 'FirstName':'First Name','LastName':'Last Name'}
    list_columns = ['CarClass.CarClassKey','CarClass.Marque','CarClass.Title','FirstName','LastName']
    show_columns = list_columns

```
But the error displayed is "TypeError: 'VotingView' object is not callable". I plan on creating a specific template for this page but first I need to know that I can call the view. I'd appreciate any help getting past this hurdle.
Thanks!
Jim

**Comment by mistercrunch** [comment]
You should comment out the `@app.route` line, the `ModelView` will create the routes on its own based on the name of the class at places like `/votingview/list`. You do need to call the function to register the model view (see examples).

Also note that I think you can specify the string of your choice instead of the default `votingview`.I think you have to override the class attribute `view_name`.

**Comment by AustinJim** [comment]
Thanks!
