### ISSUE TITLE
Mapping External roles to FAB roles

### ISSUE THREAD

**Issue by bolkedebruin** [dpgaspar/Flask-AppBuilder#518]
Hi,

I'm looking at possibilities of integrating FAB with Apache Airflow (hey @mistercrunch :) ). Some of the users of Airflow are running it in an enterprise context. This means roles are created in a centralised system and maintained there.

Ideally FAB allows for a Business Role mapping to a FAB role. For example, authentication is done by kerberos/ldap/ad and the user group in AD/LDAP/IPA/PAM defines what role one gets in FAB. I wonder if this is possible already with FAB or if this requires some additions. Prerequisite would be that FAB does not retain Users by itself to prevent clean up requirements which get really messy with 50K+ users. If so where to start (coding)?

Reading through code quickly it seems authentication can be handled externally, but authorization cannot be and is done by FAB at the moment. My first hunch would be to extend BaseSecurityManager and raise NotImplemented on anything that creates, updates, deletes, lists. Then add a new table that contains "external_source, external_role, fab_role". How does that sound? Would that be acceptable?

Cheers

**Comment by dpgaspar** [comment]
Hi,

This would require some additions (extending BaseSecurityManager is the way to go), there are several ways of doing it: 

1 - Doing it like the Atlassian tools do it, they periodically, or manually sincronize LDAP groups in to the app's db. Like you proposed this would need to go to a separate table (ab_external_role), then the 'Admin' would choose those who are FAB and associate them with permissions on views/menus. This sync would also associate the LDAP groups to the FAB user's. 

2 - Don't import any groups from LDAP, on authentication the user's roles are mapped (updated on the db) with the LDAP groups he has and have the same name. User/Roles association would be disabled on the UI.

Only create an external_source table if you would like to bring the LDAP configuration to the UI. If so, we would need to allow mix authentication LDAP/DB, so that admin's are not left out when a misconfiguration happens.

**Comment by bolkedebruin** [comment]
Thanks for the response. I don't like 1) as it creates an auditing nightmare (users are left in the db)  sometimes inherit old permissions (see Atlassian, Apache Ranger). So I was aiming for 2. Indeed doing mapping by requesting it from LDAP. The only thing you manage from FAB is the LDAP group (or whatever attribute you like) mapping to FAB role. 

So it is a small mix of DB+LDAP and I would like to leave the generic LDAP config in the config file not in the UI (I don't see that case for that).

So I am creating ldap/manager.py and ldap/models.py . In models.py I would copy the PermissionView from sqla and create a RoleMap model instead of a Role model.

**Comment by dpgaspar** [comment]
I prefer 2 also, simple is beautiful!

But why not:
- Create a new authentication type, say AUTH_LDAP_ROLE or AUTH_DB_LDAP_ROLE
- create a new 'auth_user_ldap_role' or 'auth_user_db_ldap_role' on BaseSecurityManager to authenticate and fill the user's roles on authentication from his LDAP groups
- Change role methods where needed.

This way I don't think you would need to create different models or additional ones. The current propose of security/sqla/manager.py and security/mongoengine/manager.py is to support different db backends.

Open a PR, i'll would gladly integrate it.

**Comment by bolkedebruin** [comment]
Wouldn't that still create "User" tables etc in my database? Basically I would assume that LDAP_ROLE is a different DB backend? I probably would need to build in some caching in order not to kill the LDAP server (especially in the case of Airflow).

**Comment by dpgaspar** [comment]
Yes, sorry, i see what you mean. 

"Prerequisite would be that FAB does not retain Users by itself to prevent clean up requirements which get really messy with 50K+ users"

So anyone with a certain LDAP group would be allowed to login.

And yes you have to be careful with flask_login.LoginManager.user_loader.

PS:
- consider calling it security/ldap-sqla, so that in the future we could implement security/ldap-mongoengine.
- No support next week.
- Best of luck, it would be great to see airflow using FAB.

**Comment by kevlogan90** [comment]
Airflow 1.10 now has RBAC support using FAB. Has this LDAP mapping been implemented, or has there been anymore work towards this?

From the looks of it, I'm not seeing `security/ldap-sqla`

**Comment by villebro** [comment]
Looking to revive this discussion as we are also hoping to establish a reliable mapping from LDAP/AD roles to Airflow and Superset. @bolkedebruin , was this ever completed, either in FAB, Airflow or as a custom extension/fork? If not I would be willing to chip in, as this would make access management much more transparent and secure from an enterprise perspective.

**Comment by periscube** [comment]
It would be excellent! Please do not limit it with ldap/ad also include openid connect such as OKTA if you're thinking enterprise adaptation.. In OKTA, there are groups which can be mapped to the roles in FAB.
ex:
`if 'Airflow-Administrators' in oidc.user_getinfo.get('groups'):
     role = 'Admin'
 elif 'Airflow-Ops' in oidc.user_getinfo.get('groups'):
     role = 'Op'
.....`

**Comment by bolkedebruin** [comment]
Hi,

Sorry got sidetracked. We still like it, but didnt get around on implementing it.

**Comment by thesuperzapper** [comment]
I have just created a PR in Flask-AppBuilder which implements this feature: #1374
