### ISSUE TITLE
should db.create_all() in view be used in production too?

### ISSUE THREAD

**Issue by afidegnum** [dpgaspar/Flask-AppBuilder#543]
supposed i finish with basic design and i am launching the app on a remote server, should i still leave db.create_all () inside the view or it should be removed?

**Comment by dpgaspar** [comment]
Yes, you should remove it. It will only execute on server restart, but you should have no need for it.

**Comment by MichaelPereira** [comment]
Side note: For real production use, you should look into integrating with [Flask-Migrate](https://flask-migrate.readthedocs.io/en/latest/) to use [alembic](http://alembic.zzzcomputing.com/en/latest/) to manage sql schema migrations as `db.create_all()` won't handle it (since it's not meant for that)
