### ISSUE TITLE
Bool SQLAlchemy doesn't work?

### ISSUE THREAD

**Issue by scheung38** [dpgaspar/Flask-AppBuilder#567]
```
class Contact(BaseMixin, Base):
    id = Column(Integer, primary_key=True)
    name = Column(String(150), unique=True, nullable=False)
    test = Column(Boolean, default=False)
```

Whether test is clicked or not, rendered value is always True?

**Comment by afidegnum** [comment]
you need to look at your widget session and debug which value is passed when the radio or select box is clicked

**Comment by cybersenses** [comment]
Be careful with Boolean.
It has burnt me with PostgreSQL and is not stable.

**Comment by afidegnum** [comment]
can you explain the experience you went through ?

**Comment by cybersenses** [comment]
When Updating the value of the Boolean field I had Intermittent sqlalchemy errors that was very difficult to replicate.
I had a user that kept on coming up with field not found and invalid value when updating the database though just setting the value to true or False.
Eventually I changed the code to work on integer values rather than boolean.

The bigger issue was the inconsistency. It would fail every so often and then mysteriously work again.
Will go back into older versions of the files to find this and share where the issue occurred.


Might be useful to someone.

**Comment by afidegnum** [comment]
thanks, we've taken note, but you might also look at the sql log report for more details of the error so you will know where the problem is

**Comment by cybersenses** [comment]
What I did do quite a couple of times was to look at the SQL statement generated by the update that failed and I was able to execute it directly in sql so it definitely seemed to work in the database

**Comment by passitalong** [comment]
For anyone who runs into the Boolean / Postgres issue with strict not a Boolean... Postgres and SQLAlchemy do indeed work with bool.

But I lost a week of my life to this. See: [Boolean values now cause a type error #2347](https://github.com/spotify/luigi/issues/2347)
