### ISSUE TITLE
SQLAlchemy TypeDecorator for date in format dd/mm/yyyy

### ISSUE THREAD

**Issue by pascini** [dpgaspar/Flask-AppBuilder#652]
I have had problems creating a TypeDecorator for SQLAlchemy. I need that when sending data to the BD the format most be 'yyyy-mm-dd' and when reading the data most be 'dd/mm/yyyy'. I tried to create a TypeDecorator using the code below:

    from sqlalchemy import TypeDecorator, types

              
    class DataBR(types.TypeDecorator):

    impl = types.DATE

    def process_bind_param(self, value, dialect):
        if value is not None:
            dt = value.split('-')
            value = dt[2] + '/' + dt[1] + '/' + dt[0]

        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            dt = value.split('/')
            value = dt[2] + '-' + dt[1] + '-' + dt[0]
        return value

I assign the type to the column with the line:

    birthdate = Column(DataBR, nullable = False)

Here is the error i get when run the application:

    KeyError: 'birthdate'

What am I doing wrong?

**Comment by tserafim** [comment]
> when reading the data most be 'dd/mm/yyyy'.

Just so things are more clear...what do you exactly mean by this? What is the use case? Is that date format the one you want to show on your views? Or you need that data format straight out of the database to do some computation? Or something else?

> KeyError: 'birthdate'

You didn´t provide a complete stack trace so I have to guess here...
Flask-AppBuilder was not able to recognize the `birthdate` column as a date type. You can probably find something like this on your logs: `Column birthdate Type not supported`
When it cannot recognize your data type, it is not able to automatically render a wtform.field for that column.

Depending on your use case, there are some solutions Flask-AppBuilder can handle out of the box. 
As an example, AppBuilder relies on wtforms fields, and the [DateField](http://wtforms.readthedocs.io/en/latest/fields.html#basic-fields) has a `format` attribute which default value is `%Y-%m-%d`. Maybe you can try to use another `format` argument and override the field, instead of creating a new column type?

Provide more details on your use case so people can better help you.
