### ISSUE TITLE
DateTime field shows a "DatePicker" only?

### ISSUE THREAD

**Issue by phzs** [dpgaspar/Flask-AppBuilder#685]
I've seen the fix in #22 and it seems to work as I can see the correct css class etc. when I add a DateTime field to my model (using sqlalchemy and sqlite3):
`<div class="input-group date appbuilder_datetime" id="datetimepicker">`

Nevertheless I can not choose a time (hour/minute) via the widget - only a date.
If I click on a date the current time together with the selected date gets inserted into the field. Is this normal?

[screenshot](https://ibb.co/f3Mbew)

**Comment by kurtforrester** [comment]
I can confirm the same issue.

I think it is in part related to:
https://github.com/dpgaspar/Flask-AppBuilder/blob/d95f0ed934272629ee44ad3241646fa7ba09cdf8/flask_appbuilder/static/appbuilder/js/ab.js#L50

I have retrieved the static files into my app (fabmanager collect-static) and modified the quoted line but the issue is not corrected. Not too sure where to look next...

**Comment by kurtforrester** [comment]
Additional to the javascript line referenced above it is worth noting that the ability to select time in a datetime column for filter works as expected.
https://github.com/dpgaspar/Flask-AppBuilder/blob/d95f0ed934272629ee44ad3241646fa7ba09cdf8/flask_appbuilder/static/appbuilder/js/ab_filters.js#L122-L123

**Comment by kurtforrester** [comment]
Just completed some browser testing on this:
Fedora 29
Chrome: works
Opera beta: does not work
Firefox: does not work

Windows 10:
Chrome: works
Opera: works
Edge: works

The issue is likely browser oriented and not a FAB bug.

**Comment by ashb** [comment]
@dpgaspar This is still an issue - we have DateTime model fields that are only being shown with a Date picker.
