### ISSUE TITLE
bootswatch original scss files

### ISSUE THREAD

**Issue by dolfandringa** [dpgaspar/Flask-AppBuilder#737]
I am trying to make my own theme using bootswatch but it looks like you have customized the bootswatch themes for fab. Is that right? Right now, if I make my own bootswatch theme, the resulting bootstrap.min.css overrides some of the fab appbuilder/static/appbuilder/css/bootstrap.min.css styles and results in a navbar that is messed up. 
Do you have original _variables.scss and _bootswatch.scss files used to make the fab bootswatch themes? I could use those as a start point for my theme, instead of having to reverse engineer the fab specific stuff. 

I don't want to manually override specific css directives as described in http://flask-appbuilder.readthedocs.io/en/latest/templates.html#css-and-javascript. That would be incredibly tedious for colors and stuff.

**Comment by sodevious** [comment]
👍

**Comment by dpgaspar** [comment]
I have not customised the bootswatch themes...

could it be that bootwatch version and bootrap version are somehow our of sync?

Is there a better way to include bootswatch on FAB? can you help?

**Comment by sodevious** [comment]
@dpgaspar hi!

The problem that arises as a result of including a main `bootstrap.min.css` in addition to a bootswatch theme file, is that the bootstrap system is included twice essentially. Because the bootswatch files are packaging the bootstrap core with it [as well](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/static/appbuilder/css/themes/cerulean.css). 

So this makes overriding core bootstrap styles especially tedious because those overrides need to have increased levels of specificity. 

One way you may handle this, is theming with the [source bootstrap](https://github.com/twbs/bootstrap-sass) `(.sass)` files direcrly, and using the available bootswatch `_variables.css` and `_bootswatch.scss` files to generate new minified css files that only include the core bootstrap once. It could look something like this:

```
src
| --  _bootstrap.scss (this is a manifest file that includes all the source files from bootstrap directly)
| --  _custom.scss (all the styles that are in ab.css currently)
| --  application.scss (this is a manifest file for your app, it would include the above 2 files)

| --  themes
      | --  amelia
           | --  _bootswatch.scss (directly downloaded from bootswatch.com)
           | --  _variables.scss  (directly downloaded from bootswatch.com)
           | --  amelia.scss (manifest file that includes above 2 files and _bootstrap.scss, _custom.scss) 
      | --  etc...

css
| --  application.css
| --  amelia.css
| --  etc...
```

Because the source files for the bootswatch themes would now be included in the repository, users can take it upon themselves to edit/override them easily with Sass as well -- solving @dolfandringa's issue.

**Comment by dpgaspar** [comment]
Hi @sodevious,

Thank you, are you wiling to make a PR with this? that would be great!!

**Comment by sodevious** [comment]
@dpgaspar yes I can! would you be willing to chat with me for a few minutes about it? i have some questions on the best way to handle it

**Comment by dpgaspar** [comment]
Hi @sodevious,

Thats great, send me an email, I'm sure we can arrange something.

**Comment by aboganas** [comment]
any updates on this much needed feature :)
