### ISSUE TITLE
Flask-Migrate integration

### ISSUE THREAD

**Issue by dolfandringa** [dpgaspar/Flask-AppBuilder#738]
I see a script db_migrate and db_upgrade in the bin folder, but no docs on how I am supposed to use it with flask appbuilder.
I see issue https://github.com/dpgaspar/Flask-AppBuilder/issues/373 about someone trying to integrate it themselves, and I can probably get that idea to work (I think the error there is he just doesn't import the model) but is there a way this is supposed to be integrated in flask appbuilder? Wouldn't it make sense to integrate it in fabmanager?

**Comment by dolfandringa** [comment]
I'd be happy to write some docs on it if I get some pointers.

**Comment by dolfandringa** [comment]
OK, I have it working now. I heavily borrowed ideas from [superset](https://github.com/apache/incubator-superset/tree/master/superset). It would be great if fabmanager supports flask-migrate by default (contributions welcome?). I now wrote my own flask-script cli commands to implement it. 

I made a script in app/bin/&lt;appname&gt; with the following:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import warnings
from flask.exthook import ExtDeprecationWarning
warnings.simplefilter('ignore', ExtDeprecationWarning)

from app.cli import manager

if __name__ == '__main__':
    manager.run()

```
And then in app/cli.py I implemented the command like this:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask_migrate import MigrateCommand
from flask_script import Manager

from app import app, db
from app.models import *

config = app.config


manager = Manager(app)
manager.add_command('db', MigrateCommand)
```

From there, you can start the flask-migrate stuff with ```app/bin/<appname> db init```
After that you still need to change the target_metadata in app/migrate/env.py to point to the flask_appbuilder metadata.
At the top:
```
from flask_appbuilder import Base
```
Further down, change the existing target_metadata variable to:
```
target_metadata = Base.metadata
```

This will ensure it finds your flask_appbuilder sqlalchemy metadata. If you don't, it will actually create scripts to remove all flask_appbuilder tables, because it doesn't know about them.
Then (like always with flask-migrate) run ```app/bin/<appname> db migrate``` on an empty database to create your first migration script, which will create all tables like they are currently defined in your model, and then ```app/bin/<appname> db upgrade``` to actually run the migration.

**Comment by dpgaspar** [comment]
Hi @dolfandringa ,

New 0.11.0 solves this issue, made a small quickhowto with Flask-Migrate has an example: https://github.com/dpgaspar/Flask-AppBuilder/tree/master/examples/quickmigrate

**Comment by jabbawockeez** [comment]
Hi @dpgaspar I successfully ran the quickmigrate project but I have to detect the change of column type, so I add the compare_type=True as mentioned [here](https://stackoverflow.com/questions/33944436/flask-migrate-and-changing-column-type), and then I ran it again but it stuck right before the upgrade, what is the problem here? Thanks.

**Comment by jabbawockeez** [comment]
Alright, since I use mysql as the store, I found out the problem. It's because that the type of the column "active" in the table ab_user is tinyint but is bool in model instead, so flask-migrate(alembic) detects the difference every time I try to upgrade, but as it's mentioned [here](https://github.com/miguelgrinberg/Flask-Migrate/issues/143#issuecomment-370653565), I think changing the column type to bool in mysql makes no sense, but I still don't know why it just stuck.
And one of the possible solutions is to [ignore the table in detection](https://gist.github.com/utek/6163250)
