### ISSUE TITLE
Flask-Appbuilder tables should use their own schema

### ISSUE THREAD

**Issue by WouterVH** [dpgaspar/Flask-AppBuilder#798]
When using postgresql, all ab_* tables are create in the "public"-schema.

How can we create these tables in their own schema?
Is there an easy solution available?

**Comment by dolfandringa** [comment]
Sorry for the late answer.

I guess you're talking postgresql specifically here? It is definitely possible but a bit involved because flask-sqlalchemy does much of the work for us. I havent tried this out myself, but I think this is what is involved:

SQLAlchemy allows you to configure the schema [on a metadata level](https://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.MetaData) but [also per table](https://docs.sqlalchemy.org/en/latest/core/metadata.html#specifying-the-schema-name). Any argument you can pass to the Table() function can also be passed to __table_args__ in your model classes. So in your case you could override all the relevant model classes (probably the ones in [flask_appbuilder.security.sqla.models](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/security/sqla/models.py)), define the schema in the __table_args__ and then [setup your security manager to use those classes instead](https://flask-appbuilder.readthedocs.io/en/latest/security.html#extending-the-user-model).

I hope this helps you on your way. I am closing the issue to clean up our issue queue, but feel free to re-open it if you want to discuss it further.
