### ISSUE TITLE
Add or Remove Fields Based on Permissions or Roles

### ISSUE THREAD

**Issue by poerwiyanto** [dpgaspar/Flask-AppBuilder#914]
Hi, I want to ask about add or remove fields (https://flask-appbuilder.readthedocs.io/en/latest/advanced.html#forms-add-or-remove-fields). Can I add or remove fields based on permissions or roles? For example:

add_columns = ['my_field1','my_field2']

I want 'my_field1' to appear in form if the user is admin. How can I do that? Thanks.

**Comment by soundmaking** [comment]
Hello,

I'm doing a similar thing and will describe how - but hopefully some can point to a better way!

In this app we give admin view of **all fields** and another user role only access to **a small number of fields**.  Doing this by only letting Admin access the F.A.B crud model view, and then setting up a separate view for the other role to edit with...  

in views.py I am getting user's roles as a list of strings:

```python
def get_user_role_list():
    if not g.user.is_anonymous:
        return [str(r) for r in g.user.roles] 
    else:
        return []
```

then in the def of a view doing:

```python
        user_role_list = get_user_role_list()
        user_is_coord = 'Coordinator' in user_role_list 
```

Now that I think about it, I am probably doing three or four different techniques because each time I come to a similar situation I look for a better way to do it... I'm doing a lot of Jinja `{% if statements %}` to change what buttons and blocks are shown to different users.

For what you're asking, it might be possible to extend a model view template along similar lines (?)

**Comment by poerwiyanto** [comment]
Hi, @soundmaking 

I have been able to get the current user's role. My question is how can I add or remove fields based on the role that I have? You mentioned about using Jinja, can you please provide a thorough example? Thanks.

**Comment by dpgaspar** [comment]
Hi,

There are several ways of doing this (as always). One dead simple, is to create an admin class view that includes your add_columns, and on your 'user' view suppress it. Then on security give access to the admin view class only to admins and the user view class to users.

Another way is to override and implement the add WTF form yourself and reference it on your model view class (add_template = 'my_add_form.html). (remember you have access to the security manager on the templates.

And another way, is to override the ModelView add method:

``` python
    @expose('/add', methods=['GET', 'POST'])
    @has_access
    def add(self):
        print("Do your thing here")
        return super(YourModelView, self).add()
```

**Comment by poerwiyanto** [comment]
Hi @dpgaspar 

Thank you for your answer.

"There are several ways of doing this (as always). One dead simple, is to create an admin class view that includes your add_columns, and on your 'user' view suppress it. Then on security give access to the admin view class only to admins and the user view class to users." ---> Does this mean I have to define two ModelView for two different roles?

I think I prefer the third solution, where can I read more about overriding the ModelView? Thanks.

**Comment by dpgaspar** [comment]
Yes, it does mean that.

Use plain simple method overriding and read the code. Note that the WTF form is created on class __init__. Remember also that not all use cases are covered on FAB (far from it), but you can always develop your specific needs using plain Flask, or a simple BaseView. 

Any further help needed, Open an issue, I'll try to answer it.

**Comment by poerwiyanto** [comment]
Thanks, @dpgaspar . I have tried the third solution and it worked!

**Comment by dpgaspar** [comment]
Great! don't forget (if your using FAB on a company or interesting project) to submit a PR to add it to the README:

https://github.com/dpgaspar/Flask-AppBuilder#projectsorganizations-using-fab
