### ISSUE TITLE
Why can't FAB models be used like normal SQLAlchemy models

### ISSUE THREAD

**Issue by cryptonomicon314** [dpgaspar/Flask-AppBuilder#93]
I don't get the reason why FAB can't be used the same way as SQLAlchemy models in queries. SQLAlchemy allows you to do ``User.query...``, while in FAB you have to use ``db.session.query()``. I actually prefer the later, but some flask extensions require the use of the former, and this makes them incompatible with FAB, which is undesirable. Of course, I'd rather have FAB than those extensions, but I'd like to know the reason why we can't play nice with SQLAlchemy

**Comment by dpgaspar** [comment]
Good question, in fact this was a problem a tried to solve on the early stages of this project.

The problem is that F.A.B. comes with it's own model definition (security models) i can't define this models using db.Model, because i can't import db, it's own the dev's app. So i have to define the models using **Models**. With this is mind i have to guarantee that the dev's app models are on the same declaritve space so that their models can use relations to F.A.B.'s models.

Read the paragraph: http://flask-appbuilder.readthedocs.org/en/latest/quickhowto.html#simple-contacts-application

You can use db.Model but you won't be able to make relations to the security models.

**Comment by dpgaspar** [comment]
Did this cleared the question?

**Comment by cryptonomicon314** [comment]
Yes, it did. Thank you
